### ISSUE TITLE
Get API keys

### ISSUE THREAD

**Issue by JohnKihm** [JohnKihm/FlickPicker#2]

**Comment by tedwhitson** [comment]
OMDB API Key
Mon 5/6/2024 10:19 PM
Here is your key: 79711389
Please append it to all of your API requests,
OMDb API: http://www.omdbapi.com/?i=tt3896198&apikey=79711389
Click the following URL to activate your key: http://www.omdbapi.com/apikey.aspx?VERIFYKEY=5e738452-80bf-4bc3-9b58-2b04b97aa2e9
If you did not make this request, please disregard this email.

**Comment by tedwhitson** [comment]
TMDB API Key: 7ef17cd5f1f31676a0f79646b09ad3fc
[9:33](https://kuvirtfsfpt03-lqd4793.slack.com/archives/C0721G4JHU6/p1715049216101139)
TMDB API Read Access Token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWYxN2NkNWYxZjMxNjc2YTBmNzk2NDZiMDlhZDNmYyIsInN1YiI6IjY2Mzk5MGQ5MzU4ZGE3MDEyNzU3Mjc0ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.8foFk9e5pco45zFAvPpjjD0zvKuDxT8VH6iGPv72W3s
9:34
TMDB docs: developer.themoviedb.org
